### PR TITLE
BAP-537 updated version of Artifactory buildinfo library and added mi…

### PR DESCRIPTION
**Pull request by hartjames**
updated version of Artifactory buildinfo library and added missing dependency

### CODE REVIEW

**Comment by hartjames** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by hartjames** [comment]
Need to do some additional testing.  Resolved issue in one environment but not a second environment I was testing in.

**Comment by hartjames** [comment]
Issue was with deployment of plugin to the slaves.  Fixed that and the update is working.

**Comment by yahavi** [comment]
@hartjames thanks for this contribution!
Since version 3.2.4 of the plugin, we use build-info 2.26.1 and commons-lang3:3.8.1.
Do you still have this issue?

**Comment by eyalbe4** [comment]
@hartjames -
Can this PR be closed?

**Pull request closed without merging**
